apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: web
    spec:
      restartPolicy: Always
      containers:
        - name: {{ template "airflow.fullname" . }}-web
          image: {{ .Values.airflow.image }}
          imagePullPolicy: {{ .Values.airflow.image_pull_policy}}
          envFrom:
            - configMapRef:
                name: {{ template "airflow.fullname" . }}-airflow-cfg
          ports:
            - name: web
              containerPort: 8080
          args: ["webserver"]
