apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-worker
spec:
  replicas: {{ .Values.celery.num_workers }}
  template:
    metadata:
      labels:
        app: airflow
        tier: worker
    spec:
      restartPolicy: Always
      containers:
        - name: {{ template "airflow.fullname" . }}-worker
          image: {{ .Values.airflow.image }}
          imagePullPolicy: {{ .Values.airflow.image_pull_policy}}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: dags-data
              mountPath: {{ .Values.airflow.dag_path }}
          {{ end }}
          # volumes:
          #     - /localpath/to/dags:/usr/local/airflow/dags
          envFrom:
            - configMapRef:
                name: {{ template "airflow.fullname" . }}-airflow-cfg
          args: ["worker"]
      volumes:
        - name: dags-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
              claimName: {{ .Values.persistence.existingClaim | default (include "airflow.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
