apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-flower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: flower
    spec:
      restartPolicy: Always
      containers:
        - name: {{ template "airflow.fullname" . }}-flower
          image: {{ .Values.airflow.image }}
          imagePullPolicy: {{ .Values.airflow.image_pull_policy}}
          env:
            - name: FLOWER_PORT
              value: "5555"
          envFrom:
            - configMapRef:
                name: {{ template "airflow.fullname" . }}-airflow-cfg
          ports:
            - name: flower
              containerPort: 5555
          args: ["flower"]
