apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: db
    spec:
      containers:
        - name: {{ template "airflow.fullname" . }}-postgres
          image: postgres
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.db.postgres.user -}}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.db.postgres.password -}}"
            - name: POSTGRES_DB
              value: "{{ .Values.db.postgres.database -}}"
