apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "airflow.fullname" . }}-rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        tier: rabbitmq
    spec:
      restartPolicy: Always
      containers:
        - name: {{ template "airflow.fullname" . }}-rabbitmq
          image: rabbitmq:3-management
          ports:
            - name: rabbitmq-mgmt
              containerPort: 15672
            - name: rabbitmq-node
              containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.db.rabbitmq.user -}}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.db.rabbitmq.password -}}"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "airflow"
