{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "airflow.fullname" . }}-airflow
  annotations:
    {{ range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path.web }}
            backend:
              serviceName: {{ template "airflow.fullname" . }}-web
              servicePort: {{ template "airflow.fullname" . }}-pweb
      host: {{ .Values.ingress.host }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "airflow.fullname" . }}-airflow-flower
  annotations:
    {{ range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path.flower }}
            backend:
              serviceName: {{ template "airflow.fullname" . }}-flower
              servicePort: {{ template "airflow.fullname" . }}-pflower
      host: {{ .Values.ingress.host }}
{{- end }}
