apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-postgres
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-rabbitmq
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: rabbitmq
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: rabbitmq
    - name: rabbitmq-mgmt
      protocol: TCP
      port: 15672
      targetPort: rabbitmq-mgmt
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-web
spec:
  type: NodePort
  selector:
    app: airflow
    tier: web
  ports:
    - name: web
      protocol: TCP
      port: 8080
      name: pweb
      targetPort: web
      nodePort: 32080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-flower
spec:
  type: NodePort
  selector:
    app: airflow
    tier: flower
  ports:
    - name: flower
      protocol: TCP
      port: 5555
      name: pflower
      targetPort: flower
      nodePort: 32081
